"""
https://leetcode.com/problems/reconstruct-itinerary/description/?envType=problem-list-v2&envId=graph
"""

import collections
import pathlib

import pytest


class Solution:
    def findItinerary(self, tickets: list[list[str]], *_) -> list[str]:
        start = "JFK"

        _adj_list: collections.defaultdict[str, list[str]] = collections.defaultdict(list)
        for u, v in tickets:
            _adj_list[u].append(v)

        adj_list: dict[str, list[str]] = {u: sorted(v) for u, v in _adj_list.items()}
        start_itinerary = [start]

        def dfs(src, itinerary, tail, left_tickets):
            if not left_tickets:
                return itinerary, tail, True

            if not left_tickets.get(src):
                return itinerary, tail, False

            possible_dst = list(left_tickets[src])
            # already sorted alphabetically, don't guarantee success.
            # if fails, reverts itinerary to recover point and updates tail
            for dst in possible_dst:
                if src not in left_tickets:
                    # means already explored at deeper level
                    continue

                # cut edge
                left_tickets[src].remove(dst)
                if not left_tickets[src]:
                    left_tickets.pop(src)

                new_itinerary, new_tail, new_is_success = dfs(
                    dst,
                    itinerary + [dst],
                    tail,
                    left_tickets,
                )
                if new_is_success:
                    # add tail to the end of itinerary in reversed order (we pushed the dead end first -> extract last)
                    while tail:
                        new_itinerary.append(tail.pop())
                    return new_itinerary, tail, True
                else:
                    dead_path = new_itinerary[len(itinerary) :]
                    for el in dead_path:
                        tail.append(el)

            return itinerary, tail, False

        start_tail: collections.deque[str] = collections.deque()
        final_itinerary, final_tail, is_success = dfs(
            start,
            start_itinerary,
            start_tail,
            adj_list,
        )
        return final_itinerary


def main(tickets: list[list[str]], f=None) -> list[str]:
    return Solution().findItinerary(tickets, f)


@pytest.mark.parametrize(
    "inp,expected",
    [
        pytest.param(
            dict(tickets=[["MUC", "LHR"], ["JFK", "MUC"], ["SFO", "SJC"], ["LHR", "SFO"]]),
            ["JFK", "MUC", "LHR", "SFO", "SJC"],
            # 0
        ),
        pytest.param(
            dict(tickets=[["JFK", "SFO"], ["JFK", "ATL"], ["SFO", "ATL"], ["ATL", "JFK"], ["ATL", "SFO"]]),
            ["JFK", "ATL", "JFK", "SFO", "ATL", "SFO"],
            # 1
        ),
        pytest.param(
            dict(
                tickets=[
                    ["JFK", "SFO"],
                    ["JFK", "ATL"],
                    ["SFO", "JFK"],
                    ["ATL", "AAA"],
                    ["AAA", "ATL"],
                    ["ATL", "BBB"],
                    ["BBB", "ATL"],
                    ["ATL", "CCC"],
                    ["CCC", "ATL"],
                    ["ATL", "DDD"],
                    ["DDD", "ATL"],
                    ["ATL", "EEE"],
                    ["EEE", "ATL"],
                    ["ATL", "FFF"],
                    ["FFF", "ATL"],
                    ["ATL", "GGG"],
                    ["GGG", "ATL"],
                    ["ATL", "HHH"],
                    ["HHH", "ATL"],
                    ["ATL", "III"],
                    ["III", "ATL"],
                    ["ATL", "JJJ"],
                    ["JJJ", "ATL"],
                    ["ATL", "KKK"],
                    ["KKK", "ATL"],
                    ["ATL", "LLL"],
                    ["LLL", "ATL"],
                    ["ATL", "MMM"],
                    ["MMM", "ATL"],
                    ["ATL", "NNN"],
                    ["NNN", "ATL"],
                ],
            ),
            [
                "JFK",
                "SFO",
                "JFK",
                "ATL",
                "AAA",
                "ATL",
                "BBB",
                "ATL",
                "CCC",
                "ATL",
                "DDD",
                "ATL",
                "EEE",
                "ATL",
                "FFF",
                "ATL",
                "GGG",
                "ATL",
                "HHH",
                "ATL",
                "III",
                "ATL",
                "JJJ",
                "ATL",
                "KKK",
                "ATL",
                "LLL",
                "ATL",
                "MMM",
                "ATL",
                "NNN",
                "ATL",
            ],
            # 2
            #           AAA ←→
            #           BBB ←→
            #           CCC ←→
            #           DDD ←→
            #           EEE ←→
            #           FFF ←→
            #           GGG ←→
            #           HHH ←→
            #           III ←→
            #           JJJ ←→
            #           KKK ←→
            #           LLL ←→
            #           MMM ←→
            #           NNN ←→
            #              ↑
            #              |
            # SFO ←→ JFK → ATL
        ),
        pytest.param(
            dict(tickets=[["JFK", "KUL"], ["JFK", "NRT"], ["NRT", "JFK"]]),
            ["JFK", "NRT", "JFK", "KUL"],
            # 3
        ),
        pytest.param(
            dict(
                tickets=[
                    ["EZE", "AXA"],
                    ["TIA", "ANU"],
                    ["ANU", "JFK"],
                    ["JFK", "ANU"],
                    ["ANU", "EZE"],
                    ["TIA", "ANU"],
                    ["AXA", "TIA"],
                    ["TIA", "JFK"],
                    ["ANU", "TIA"],
                    ["JFK", "TIA"],
                ],
            ),
            ["JFK", "ANU", "EZE", "AXA", "TIA", "ANU", "JFK", "TIA", "ANU", "TIA", "JFK"],
            # 4
        ),
        pytest.param(
            dict(
                tickets=[
                    ["AUA", "EZE"],
                    ["JFK", "AUA"],
                    ["EZE", "ANU"],
                    ["AXA", "JFK"],
                    ["AUA", "JFK"],
                    ["ADL", "TIA"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["AUA", "AXA"],
                    ["AXA", "TIA"],
                    ["EZE", "AXA"],
                    ["AXA", "AUA"],
                    ["ANU", "JFK"],
                    ["ADL", "EZE"],
                    ["ADL", "ANU"],
                    ["EZE", "ADL"],
                    ["AXA", "AUA"],
                    ["JFK", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["AXA", "JFK"],
                    ["ADL", "EZE"],
                    ["AUA", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["JFK", "AXA"],
                    ["TIA", "AXA"],
                    ["JFK", "ADL"],
                    ["ADL", "AXA"],
                    ["AXA", "AUA"],
                    ["AUA", "AXA"],
                    ["JFK", "AXA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["JFK", "AXA"],
                    ["EZE", "AXA"],
                    ["AXA", "EZE"],
                    ["JFK", "ADL"],
                    ["EZE", "AXA"],
                    ["ANU", "AXA"],
                    ["AXA", "JFK"],
                    ["JFK", "AUA"],
                    ["AXA", "EZE"],
                    ["ADL", "AXA"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["AXA", "AUA"],
                    ["ADL", "ANU"],
                    ["ANU", "AUA"],
                    ["ADL", "ANU"],
                    ["JFK", "ADL"],
                    ["TIA", "AUA"],
                    ["EZE", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "ADL"],
                    ["JFK", "ANU"],
                    ["ADL", "ANU"],
                    ["TIA", "AUA"],
                    ["ADL", "ANU"],
                    ["AUA", "EZE"],
                    ["JFK", "ANU"],
                    ["AUA", "ANU"],
                    ["ADL", "AUA"],
                    ["JFK", "ADL"],
                    ["TIA", "JFK"],
                    ["AXA", "ANU"],
                    ["AXA", "ANU"],
                    ["JFK", "AXA"],
                    ["AXA", "JFK"],
                    ["ANU", "AXA"],
                    ["ADL", "EZE"],
                    ["JFK", "ANU"],
                    ["JFK", "AUA"],
                    ["AXA", "ANU"],
                    ["JFK", "TIA"],
                    ["ANU", "AXA"],
                    ["JFK", "AUA"],
                    ["AXA", "AUA"],
                    ["ADL", "EZE"],
                    ["ADL", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "AUA"],
                    ["AUA", "ADL"],
                    ["JFK", "ADL"],
                    ["EZE", "TIA"],
                    ["TIA", "AXA"],
                    ["AUA", "ADL"],
                    ["JFK", "AUA"],
                    ["JFK", "AUA"],
                    ["AUA", "ANU"],
                    ["JFK", "ADL"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "ADL"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["EZE", "ANU"],
                    ["AUA", "ANU"],
                    ["JFK", "EZE"],
                    ["EZE", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["TIA", "ANU"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["AXA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "ANU"],
                    ["EZE", "AXA"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["TIA", "JFK"],
                    ["JFK", "AUA"],
                    ["ADL", "AUA"],
                    ["AXA", "TIA"],
                    ["AXA", "TIA"],
                    ["AXA", "ANU"],
                    ["AUA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["ANU", "TIA"],
                    ["AUA", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "EZE"],
                    ["AXA", "JFK"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["AUA", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["EZE", "ADL"],
                    ["ADL", "ANU"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "HBA"],
                    ["JFK", "AUA"],
                    ["TIA", "AUA"],
                    ["TIA", "ADL"],
                    ["AXA", "ADL"],
                    ["EZE", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "TIA"],
                    ["ANU", "JFK"],
                    ["EZE", "AUA"],
                    ["EZE", "AUA"],
                    ["ADL", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "AXA"],
                    ["AXA", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["ANU", "JFK"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["ADL", "JFK"],
                    ["JFK", "ANU"],
                    ["ADL", "JFK"],
                    ["ANU", "AUA"],
                    ["JFK", "ADL"],
                    ["AXA", "ANU"],
                    ["AXA", "JFK"],
                    ["JFK", "ADL"],
                    ["EZE", "JFK"],
                    ["TIA", "AUA"],
                    ["ANU", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AXA"],
                    ["AUA", "JFK"],
                    ["ADL", "AXA"],
                    ["EZE", "ANU"],
                    ["TIA", "EZE"],
                    ["EZE", "JFK"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["AUA", "JFK"],
                    ["ANU", "JFK"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AXA", "ADL"],
                    ["JFK", "TIA"],
                    ["AUA", "ADL"],
                    ["EZE", "TIA"],
                    ["AXA", "EZE"],
                    ["EZE", "AUA"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["TIA", "ANU"],
                    ["AXA", "JFK"],
                    ["TIA", "EZE"],
                    ["EZE", "ANU"],
                    ["ANU", "EZE"],
                    ["JFK", "TIA"],
                    ["JFK", "EZE"],
                    ["TIA", "AXA"],
                    ["ANU", "EZE"],
                    ["AUA", "TIA"],
                    ["AXA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "EZE"],
                    ["AUA", "EZE"],
                    ["ADL", "ANU"],
                    ["AUA", "AXA"],
                    ["AXA", "ADL"],
                    ["JFK", "EZE"],
                ],
            ),
            [
                "JFK",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ANU",
                "AUA",
                "ANU",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "AUA",
                "ANU",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "EZE",
                "ADL",
                "AXA",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "EZE",
                "AUA",
                "EZE",
                "AXA",
                "EZE",
                "AXA",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "TIA",
                "ADL",
                "TIA",
                "ANU",
                "TIA",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "TIA",
                "AUA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "TIA",
                "EZE",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "AUA",
                "HBA",
            ],
            # 5
        ),
        pytest.param(
            dict(
                tickets=[
                    ["AUA", "EZE"],
                    ["JFK", "AUA"],
                    ["EZE", "ANU"],
                    ["AXA", "JFK"],
                    ["AUA", "JFK"],
                    ["ADL", "TIA"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["AUA", "AXA"],
                    ["AXA", "TIA"],
                    ["EZE", "AXA"],
                    ["AXA", "AUA"],
                    ["ANU", "JFK"],
                    ["ADL", "EZE"],
                    ["ADL", "ANU"],
                    ["EZE", "ADL"],
                    ["AXA", "AUA"],
                    ["JFK", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["AXA", "JFK"],
                    ["ADL", "EZE"],
                    ["AUA", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["JFK", "AXA"],
                    ["TIA", "AXA"],
                    ["JFK", "ADL"],
                    ["ADL", "AXA"],
                    ["AXA", "AUA"],
                    ["AUA", "AXA"],
                    ["JFK", "AXA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["JFK", "AXA"],
                    ["EZE", "AXA"],
                    ["AXA", "EZE"],
                    ["JFK", "ADL"],
                    ["EZE", "AXA"],
                    ["ANU", "AXA"],
                    ["AXA", "JFK"],
                    ["JFK", "AUA"],
                    ["AXA", "EZE"],
                    ["ADL", "AXA"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["AXA", "AUA"],
                    ["ADL", "ANU"],
                    ["ANU", "AUA"],
                    ["ADL", "ANU"],
                    ["JFK", "ADL"],
                    ["TIA", "AUA"],
                    ["EZE", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "ADL"],
                    ["JFK", "ANU"],
                    ["ADL", "ANU"],
                    ["TIA", "AUA"],
                    ["ADL", "ANU"],
                    ["AUA", "EZE"],
                    ["JFK", "ANU"],
                    ["AUA", "ANU"],
                    ["ADL", "AUA"],
                    ["JFK", "ADL"],
                    ["TIA", "JFK"],
                    ["AXA", "ANU"],
                    ["AXA", "ANU"],
                    ["JFK", "AXA"],
                    ["AXA", "JFK"],
                    ["ANU", "AXA"],
                    ["ADL", "EZE"],
                    ["JFK", "ANU"],
                    ["JFK", "AUA"],
                    ["AXA", "ANU"],
                    ["JFK", "TIA"],
                    ["ANU", "AXA"],
                    ["JFK", "AUA"],
                    ["AXA", "AUA"],
                    ["ADL", "EZE"],
                    ["ADL", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "AUA"],
                    ["AUA", "ADL"],
                    ["JFK", "ADL"],
                    ["EZE", "TIA"],
                    ["TIA", "AXA"],
                    ["AUA", "ADL"],
                    ["JFK", "AUA"],
                    ["JFK", "AUA"],
                    ["AUA", "ANU"],
                    ["JFK", "ADL"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "ADL"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["EZE", "ANU"],
                    ["AUA", "ANU"],
                    ["JFK", "EZE"],
                    ["EZE", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["TIA", "ANU"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["AXA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "ANU"],
                    ["EZE", "AXA"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["TIA", "JFK"],
                    ["JFK", "AUA"],
                    ["ADL", "AUA"],
                    ["AXA", "TIA"],
                    ["AXA", "TIA"],
                    ["AXA", "ANU"],
                    ["AUA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["ANU", "TIA"],
                    ["AUA", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "EZE"],
                    ["AXA", "JFK"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["AUA", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["EZE", "ADL"],
                    ["ADL", "ANU"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "HBA"],
                    ["JFK", "AUA"],
                    ["TIA", "AUA"],
                    ["TIA", "ADL"],
                    ["AXA", "ADL"],
                    ["EZE", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "TIA"],
                    ["ANU", "JFK"],
                    ["EZE", "AUA"],
                    ["EZE", "AUA"],
                    ["ADL", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "AXA"],
                    ["AXA", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["ANU", "JFK"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["ADL", "JFK"],
                    ["JFK", "ANU"],
                    ["ADL", "JFK"],
                    ["ANU", "AUA"],
                    ["JFK", "ADL"],
                    ["AXA", "ANU"],
                    ["AXA", "JFK"],
                    ["JFK", "ADL"],
                    ["EZE", "JFK"],
                    ["TIA", "AUA"],
                    ["ANU", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AXA"],
                    ["AUA", "JFK"],
                    ["ADL", "AXA"],
                    ["EZE", "ANU"],
                    ["TIA", "EZE"],
                    ["EZE", "JFK"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["AUA", "JFK"],
                    ["ANU", "JFK"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AXA", "ADL"],
                    ["JFK", "TIA"],
                    ["AUA", "ADL"],
                    ["EZE", "TIA"],
                    ["AXA", "EZE"],
                    ["EZE", "AUA"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["TIA", "ANU"],
                    ["AXA", "JFK"],
                    ["TIA", "EZE"],
                    ["EZE", "ANU"],
                    ["ANU", "EZE"],
                    ["JFK", "TIA"],
                    ["JFK", "EZE"],
                    ["TIA", "AXA"],
                    ["ANU", "EZE"],
                    ["AUA", "TIA"],
                    ["AXA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "EZE"],
                    ["AUA", "EZE"],
                    ["ADL", "ANU"],
                    ["AUA", "AXA"],
                    ["AXA", "ADL"],
                    ["JFK", "EZE"],
                ],
            ),
            [
                "JFK",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ANU",
                "AUA",
                "ANU",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "AUA",
                "ANU",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "EZE",
                "ADL",
                "AXA",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "EZE",
                "AUA",
                "EZE",
                "AXA",
                "EZE",
                "AXA",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "TIA",
                "ADL",
                "TIA",
                "ANU",
                "TIA",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "TIA",
                "AUA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "TIA",
                "EZE",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "AUA",
                "HBA",
            ],
            # 6
        ),
        pytest.param(
            dict(
                tickets=[
                    ["HBA", "MEL"],
                    ["ASD", "CNS"],
                    ["AXA", "SYD"],
                    ["BIM", "TIA"],
                    ["AUA", "TCB"],
                    ["TBI", "BZE"],
                    ["PER", "CBR"],
                    ["CNS", "TCB"],
                    ["ADL", "ASD"],
                    ["ELH", "BAK"],
                    ["HBA", "OOL"],
                    ["CBR", "ADL"],
                    ["CNS", "AUA"],
                    ["ADL", "TBI"],
                    ["MEL", "TBI"],
                    ["ELH", "BAK"],
                    ["TIA", "BNE"],
                    ["ANU", "VIE"],
                    ["TCB", "BAK"],
                    ["TCB", "ADL"],
                    ["VIE", "TCB"],
                    ["BAK", "VIE"],
                    ["ASD", "PER"],
                    ["INN", "HBA"],
                    ["TCB", "LST"],
                    ["CNS", "DRW"],
                    ["DRW", "AXA"],
                    ["ANU", "CNS"],
                    ["SYD", "BNE"],
                    ["ADL", "SYD"],
                    ["MEL", "SYD"],
                    ["MHH", "TIA"],
                    ["TIA", "ADL"],
                    ["DRW", "TCB"],
                    ["ADL", "EZE"],
                    ["INN", "MHH"],
                    ["BIM", "TIA"],
                    ["HBA", "AXA"],
                    ["INN", "CNS"],
                    ["INN", "TBI"],
                    ["TCB", "AXA"],
                    ["EZE", "ADL"],
                    ["DRW", "HBA"],
                    ["DRW", "EZE"],
                    ["TIA", "OOL"],
                    ["OOL", "BAK"],
                    ["VIE", "BAK"],
                    ["HBA", "SYD"],
                    ["ADL", "CBR"],
                    ["SYD", "BIM"],
                    ["AXA", "DRW"],
                    ["AXA", "MHH"],
                    ["SYD", "TCB"],
                    ["TIA", "CNS"],
                    ["MEL", "BIM"],
                    ["TCB", "TIA"],
                    ["JFK", "INN"],
                    ["CNS", "ADL"],
                    ["BNE", "SYD"],
                    ["DRW", "SYD"],
                    ["AXA", "ASD"],
                    ["TBI", "BAK"],
                    ["BIM", "MEL"],
                    ["PER", "ASD"],
                    ["BAK", "DRW"],
                    ["BNE", "DRW"],
                    ["ASD", "TIA"],
                    ["ADL", "EZE"],
                    ["PER", "TCB"],
                    ["DRW", "OOL"],
                    ["SYD", "ADL"],
                    ["EZE", "CNS"],
                    ["ASD", "CBR"],
                    ["ADL", "VIE"],
                    ["TBI", "DRW"],
                    ["CBR", "OOL"],
                    ["ASD", "TCB"],
                    ["JFK", "MEL"],
                    ["BAK", "JFK"],
                    ["SYD", "PER"],
                    ["ASD", "MHH"],
                    ["TCB", "ELH"],
                    ["BAK", "ELH"],
                    ["ELH", "OOL"],
                    ["CBR", "BAK"],
                    ["ELH", "ANU"],
                    ["PER", "AXA"],
                    ["VIE", "ANU"],
                    ["MEL", "HBA"],
                    ["TIA", "SYD"],
                    ["SYD", "CBR"],
                    ["SYD", "JFK"],
                    ["BNE", "TIA"],
                    ["MEL", "DRW"],
                    ["SYD", "MEL"],
                    ["TIA", "BNE"],
                    ["TBI", "CNS"],
                    ["SYD", "HBA"],
                    ["LST", "OOL"],
                    ["ANU", "MEL"],
                    ["JFK", "ASD"],
                    ["VIE", "TBI"],
                    ["CBR", "CNS"],
                    ["LST", "BNE"],
                    ["ASD", "HBA"],
                    ["ANU", "INN"],
                    ["PER", "TCB"],
                    ["MEL", "BAK"],
                    ["TIA", "MHH"],
                    ["BAK", "ELH"],
                    ["TBI", "EZE"],
                    ["ADL", "AXA"],
                    ["AXA", "CNS"],
                    ["BNE", "PER"],
                    ["ADL", "MEL"],
                    ["ADL", "EZE"],
                    ["ASD", "JFK"],
                    ["MEL", "ELH"],
                    ["TIA", "TBI"],
                    ["TCB", "ASD"],
                    ["JFK", "BNE"],
                    ["ADL", "CNS"],
                    ["MEL", "HBA"],
                    ["TIA", "BIM"],
                    ["MEL", "AXA"],
                    ["ELH", "HBA"],
                    ["OOL", "HBA"],
                    ["CBR", "MHH"],
                    ["LST", "SYD"],
                    ["HBA", "ADL"],
                    ["CBR", "JFK"],
                    ["ELH", "LST"],
                    ["BIM", "TCB"],
                    ["SYD", "HBA"],
                    ["CBR", "VIE"],
                    ["MEL", "TCB"],
                    ["HBA", "ANU"],
                    ["VIE", "ELH"],
                    ["HBA", "INN"],
                    ["CNS", "LST"],
                    ["OOL", "DRW"],
                    ["LST", "PER"],
                    ["SYD", "AXA"],
                    ["AXA", "VIE"],
                    ["ANU", "DRW"],
                    ["ELH", "TIA"],
                    ["BAK", "ASD"],
                    ["HBA", "OOL"],
                    ["ADL", "BIM"],
                    ["EZE", "MEL"],
                    ["CBR", "MEL"],
                    ["DRW", "ASD"],
                    ["TCB", "DRW"],
                    ["ELH", "MHH"],
                    ["EZE", "JFK"],
                    ["ASD", "CBR"],
                    ["AXA", "INN"],
                    ["CNS", "TIA"],
                    ["TBI", "AUA"],
                    ["MHH", "LST"],
                    ["INN", "BIM"],
                    ["ADL", "EZE"],
                    ["PER", "ADL"],
                    ["PER", "ADL"],
                    ["AXA", "TCB"],
                    ["HBA", "ELH"],
                    ["ADL", "DRW"],
                    ["BAK", "LST"],
                    ["CNS", "INN"],
                    ["BIM", "VIE"],
                    ["TCB", "TBI"],
                    ["EZE", "ADL"],
                    ["CBR", "INN"],
                    ["SYD", "TCB"],
                    ["ADL", "ASD"],
                    ["BAK", "ASD"],
                    ["ASD", "VIE"],
                    ["MHH", "CBR"],
                    ["DRW", "HBA"],
                    ["MEL", "TIA"],
                    ["PER", "TIA"],
                    ["BIM", "TCB"],
                    ["TIA", "ADL"],
                    ["TBI", "BIM"],
                    ["VIE", "OOL"],
                    ["JFK", "PER"],
                    ["TBI", "TCB"],
                    ["HBA", "ANU"],
                    ["TCB", "MEL"],
                    ["TIA", "VIE"],
                    ["CNS", "BAK"],
                    ["VIE", "ASD"],
                    ["ELH", "SYD"],
                    ["MHH", "ELH"],
                    ["HBA", "ADL"],
                    ["LST", "CNS"],
                    ["INN", "ELH"],
                    ["EZE", "HBA"],
                    ["MEL", "INN"],
                    ["VIE", "INN"],
                    ["ADL", "CBR"],
                    ["ADL", "JFK"],
                    ["OOL", "TCB"],
                    ["HBA", "ADL"],
                    ["CBR", "EZE"],
                    ["BNE", "SYD"],
                    ["ELH", "DRW"],
                    ["OOL", "LST"],
                    ["DRW", "ASD"],
                    ["BNE", "ADL"],
                    ["TCB", "PER"],
                    ["OOL", "VIE"],
                    ["AUA", "HBA"],
                    ["HBA", "TIA"],
                    ["TBI", "AUA"],
                    ["EZE", "SYD"],
                    ["AXA", "PER"],
                    ["OOL", "MHH"],
                    ["CBR", "ELH"],
                    ["TCB", "VIE"],
                    ["MHH", "ELH"],
                    ["TBI", "HBA"],
                    ["HBA", "AXA"],
                    ["ASD", "MEL"],
                    ["TIA", "ANU"],
                    ["VIE", "ADL"],
                    ["AXA", "TBI"],
                    ["EZE", "ANU"],
                    ["CBR", "BNE"],
                    ["BNE", "TIA"],
                    ["OOL", "VIE"],
                    ["AXA", "PER"],
                    ["DRW", "ADL"],
                    ["JFK", "TIA"],
                    ["TIA", "CNS"],
                    ["INN", "MEL"],
                    ["BAK", "HBA"],
                    ["BIM", "HBA"],
                    ["VIE", "SYD"],
                    ["OOL", "TIA"],
                    ["VIE", "DRW"],
                    ["CNS", "TBI"],
                    ["AUA", "LST"],
                    ["TCB", "BIM"],
                    ["BIM", "TBI"],
                    ["TIA", "JFK"],
                    ["VIE", "CBR"],
                    ["HBA", "AXA"],
                    ["HBA", "BAK"],
                    ["JFK", "DRW"],
                    ["INN", "CNS"],
                    ["ANU", "VIE"],
                    ["EZE", "HBA"],
                    ["INN", "BNE"],
                    ["ADL", "MEL"],
                    ["PER", "ANU"],
                    ["TCB", "TBI"],
                    ["MEL", "CBR"],
                    ["DRW", "AXA"],
                    ["CBR", "OOL"],
                    ["BAK", "TIA"],
                    ["SYD", "PER"],
                    ["LST", "ADL"],
                    ["CNS", "INN"],
                    ["ANU", "CBR"],
                    ["MHH", "EZE"],
                    ["DRW", "MEL"],
                    ["CNS", "ELH"],
                    ["TCB", "EZE"],
                    ["DRW", "SYD"],
                    ["ADL", "DRW"],
                    ["ANU", "OOL"],
                    ["ELH", "CBR"],
                    ["TIA", "CBR"],
                    ["VIE", "ADL"],
                    ["DRW", "AXA"],
                    ["TCB", "ADL"],
                    ["CNS", "VIE"],
                    ["MHH", "ANU"],
                    ["JFK", "TCB"],
                    ["LST", "CBR"],
                    ["OOL", "BIM"],
                ],
            ),
            [
                "JFK",
                "ASD",
                "CBR",
                "ADL",
                "ASD",
                "CBR",
                "BAK",
                "ASD",
                "CNS",
                "ADL",
                "ASD",
                "HBA",
                "ADL",
                "AXA",
                "ASD",
                "JFK",
                "BNE",
                "ADL",
                "BIM",
                "HBA",
                "ADL",
                "CBR",
                "BNE",
                "DRW",
                "ADL",
                "CBR",
                "CNS",
                "AUA",
                "HBA",
                "ADL",
                "CNS",
                "BAK",
                "ASD",
                "MEL",
                "AXA",
                "CNS",
                "DRW",
                "ASD",
                "MHH",
                "ANU",
                "CBR",
                "ELH",
                "ANU",
                "CNS",
                "ELH",
                "BAK",
                "DRW",
                "ASD",
                "PER",
                "ADL",
                "DRW",
                "AXA",
                "DRW",
                "AXA",
                "INN",
                "BIM",
                "MEL",
                "BAK",
                "ELH",
                "BAK",
                "ELH",
                "CBR",
                "EZE",
                "ADL",
                "DRW",
                "AXA",
                "MHH",
                "CBR",
                "INN",
                "BNE",
                "PER",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ANU",
                "DRW",
                "EZE",
                "CNS",
                "INN",
                "CNS",
                "INN",
                "CNS",
                "LST",
                "ADL",
                "EZE",
                "HBA",
                "ANU",
                "INN",
                "ELH",
                "DRW",
                "HBA",
                "ANU",
                "MEL",
                "BIM",
                "TBI",
                "AUA",
                "LST",
                "BNE",
                "SYD",
                "ADL",
                "EZE",
                "HBA",
                "AXA",
                "PER",
                "ANU",
                "OOL",
                "BAK",
                "HBA",
                "AXA",
                "PER",
                "ASD",
                "TCB",
                "ADL",
                "JFK",
                "DRW",
                "HBA",
                "AXA",
                "SYD",
                "AXA",
                "TBI",
                "AUA",
                "TCB",
                "ADL",
                "MEL",
                "CBR",
                "JFK",
                "INN",
                "HBA",
                "BAK",
                "JFK",
                "MEL",
                "DRW",
                "MEL",
                "ELH",
                "HBA",
                "ELH",
                "LST",
                "CBR",
                "MEL",
                "HBA",
                "INN",
                "MEL",
                "HBA",
                "MEL",
                "INN",
                "MHH",
                "ELH",
                "MHH",
                "ELH",
                "OOL",
                "BIM",
                "TCB",
                "ASD",
                "TIA",
                "ADL",
                "MEL",
                "SYD",
                "BIM",
                "TCB",
                "AXA",
                "TCB",
                "BAK",
                "LST",
                "CNS",
                "TBI",
                "BAK",
                "TIA",
                "ADL",
                "SYD",
                "BNE",
                "SYD",
                "CBR",
                "MHH",
                "EZE",
                "JFK",
                "PER",
                "AXA",
                "VIE",
                "ADL",
                "TBI",
                "BIM",
                "TIA",
                "ANU",
                "VIE",
                "ADL",
                "VIE",
                "ANU",
                "VIE",
                "ASD",
                "VIE",
                "BAK",
                "VIE",
                "CBR",
                "OOL",
                "DRW",
                "OOL",
                "HBA",
                "OOL",
                "LST",
                "OOL",
                "MHH",
                "LST",
                "PER",
                "CBR",
                "OOL",
                "TCB",
                "BIM",
                "TIA",
                "BIM",
                "VIE",
                "DRW",
                "SYD",
                "HBA",
                "OOL",
                "TIA",
                "BNE",
                "TIA",
                "BNE",
                "TIA",
                "CBR",
                "VIE",
                "ELH",
                "SYD",
                "HBA",
                "SYD",
                "JFK",
                "TCB",
                "DRW",
                "SYD",
                "MEL",
                "TBI",
                "CNS",
                "TCB",
                "ELH",
                "TIA",
                "CNS",
                "TIA",
                "CNS",
                "VIE",
                "INN",
                "TBI",
                "DRW",
                "TCB",
                "EZE",
                "MEL",
                "TCB",
                "LST",
                "SYD",
                "PER",
                "TCB",
                "MEL",
                "TIA",
                "JFK",
                "TIA",
                "MHH",
                "TIA",
                "OOL",
                "VIE",
                "OOL",
                "VIE",
                "SYD",
                "PER",
                "TCB",
                "PER",
                "TIA",
                "SYD",
                "TCB",
                "TBI",
                "EZE",
                "SYD",
                "TCB",
                "TBI",
                "HBA",
                "TIA",
                "TBI",
                "TCB",
                "TIA",
                "VIE",
                "TCB",
                "VIE",
                "TBI",
                "BZE",
            ],
            # 7
        ),
        pytest.param(
            dict(
                tickets=[
                    ["MHH", "VIE"],
                    ["ADL", "TCB"],
                    ["TIA", "HBA"],
                    ["PER", "SYD"],
                    ["TIA", "ADL"],
                    ["VIE", "PER"],
                    ["AXA", "BNE"],
                    ["JFK", "CBR"],
                    ["ADL", "TCB"],
                    ["PER", "EZE"],
                    ["ADL", "PER"],
                    ["MEL", "PER"],
                    ["AUA", "BNE"],
                    ["CNS", "INN"],
                    ["JFK", "TCB"],
                    ["BAK", "EZE"],
                    ["MEL", "AUA"],
                    ["HBA", "OOL"],
                    ["BAK", "MEL"],
                    ["ADL", "INN"],
                    ["TIA", "BNE"],
                    ["OOL", "BNE"],
                    ["SYD", "EZE"],
                    ["CBR", "MEL"],
                    ["TCB", "ADL"],
                    ["EZE", "PER"],
                    ["AUA", "EZE"],
                    ["CBR", "ANU"],
                    ["BNE", "AUA"],
                    ["LST", "SYD"],
                    ["AXA", "VIE"],
                    ["LST", "VIE"],
                    ["PER", "BAK"],
                    ["JFK", "MHH"],
                    ["CBR", "DRW"],
                    ["JFK", "HBA"],
                    ["VIE", "HBA"],
                    ["MHH", "AXA"],
                    ["CNS", "AXA"],
                    ["PER", "TIA"],
                    ["INN", "DRW"],
                    ["DRW", "ADL"],
                    ["JFK", "TCB"],
                    ["SYD", "MHH"],
                    ["PER", "CBR"],
                    ["ANU", "AXA"],
                    ["VIE", "MEL"],
                    ["CNS", "JFK"],
                    ["ANU", "TCB"],
                    ["VIE", "TCB"],
                    ["SYD", "CNS"],
                    ["SYD", "PER"],
                    ["LST", "INN"],
                    ["AUA", "OOL"],
                    ["JFK", "CNS"],
                    ["HBA", "JFK"],
                    ["AXA", "EZE"],
                    ["SYD", "CNS"],
                    ["AUA", "VIE"],
                    ["PER", "CNS"],
                    ["SYD", "INN"],
                    ["DRW", "BNE"],
                    ["AXA", "JFK"],
                    ["DRW", "OOL"],
                    ["BNE", "EZE"],
                    ["ANU", "JFK"],
                    ["AXA", "HBA"],
                    ["SYD", "BNE"],
                    ["CNS", "MEL"],
                    ["HBA", "AXA"],
                    ["EZE", "ADL"],
                    ["HBA", "MEL"],
                    ["AXA", "BNE"],
                    ["TIA", "OOL"],
                    ["TCB", "BNE"],
                    ["MHH", "AUA"],
                    ["MEL", "INN"],
                    ["INN", "JFK"],
                    ["CNS", "VIE"],
                    ["AUA", "PER"],
                    ["DRW", "SYD"],
                    ["INN", "MHH"],
                    ["EZE", "MHH"],
                    ["BAK", "PER"],
                    ["BAK", "VIE"],
                    ["VIE", "MHH"],
                    ["TCB", "TIA"],
                    ["JFK", "BNE"],
                    ["VIE", "BAK"],
                    ["EZE", "SYD"],
                    ["VIE", "CNS"],
                    ["BNE", "DRW"],
                    ["ADL", "AXA"],
                    ["ANU", "DRW"],
                    ["JFK", "AUA"],
                    ["MEL", "INN"],
                    ["BNE", "JFK"],
                    ["INN", "PER"],
                    ["TIA", "AUA"],
                    ["EZE", "LST"],
                    ["ANU", "PER"],
                    ["HBA", "AUA"],
                    ["INN", "DRW"],
                    ["BNE", "SYD"],
                    ["EZE", "AXA"],
                    ["BNE", "HBA"],
                    ["VIE", "ANU"],
                    ["MEL", "TIA"],
                    ["ANU", "CNS"],
                    ["AUA", "EZE"],
                    ["OOL", "VIE"],
                    ["TCB", "MHH"],
                    ["CBR", "VIE"],
                    ["CBR", "AUA"],
                    ["LST", "PER"],
                    ["TIA", "TCB"],
                    ["AUA", "BNE"],
                    ["PER", "TIA"],
                    ["TCB", "VIE"],
                    ["INN", "DRW"],
                    ["SYD", "JFK"],
                    ["PER", "ADL"],
                    ["AUA", "EZE"],
                    ["AUA", "JFK"],
                    ["HBA", "SYD"],
                    ["BAK", "DRW"],
                    ["CNS", "MHH"],
                    ["AXA", "EZE"],
                    ["AXA", "ANU"],
                    ["CNS", "AXA"],
                    ["OOL", "BAK"],
                    ["BAK", "MEL"],
                    ["DRW", "LST"],
                    ["BNE", "OOL"],
                    ["EZE", "DRW"],
                    ["BAK", "CNS"],
                    ["CNS", "LST"],
                    ["BNE", "TCB"],
                    ["JFK", "TCB"],
                    ["PER", "OOL"],
                    ["ADL", "OOL"],
                    ["ADL", "LST"],
                    ["MHH", "SYD"],
                    ["MEL", "TCB"],
                    ["INN", "MEL"],
                    ["OOL", "EZE"],
                    ["PER", "SYD"],
                    ["OOL", "ADL"],
                    ["BNE", "MEL"],
                    ["ADL", "BAK"],
                    ["AXA", "MEL"],
                    ["INN", "VIE"],
                    ["TCB", "BNE"],
                    ["BAK", "SYD"],
                    ["BNE", "LST"],
                    ["BAK", "LST"],
                    ["INN", "BAK"],
                    ["BNE", "JFK"],
                    ["BAK", "HBA"],
                    ["SYD", "TCB"],
                    ["ADL", "SYD"],
                    ["SYD", "BNE"],
                    ["ANU", "LST"],
                    ["HBA", "TCB"],
                    ["MEL", "TIA"],
                    ["OOL", "INN"],
                    ["AXA", "TIA"],
                    ["MHH", "HBA"],
                    ["EZE", "CBR"],
                    ["LST", "SYD"],
                    ["TIA", "CBR"],
                    ["OOL", "HBA"],
                    ["ADL", "INN"],
                    ["VIE", "ANU"],
                    ["MEL", "PER"],
                    ["JFK", "AXA"],
                    ["OOL", "ADL"],
                    ["OOL", "AXA"],
                    ["TCB", "PER"],
                    ["VIE", "BAK"],
                    ["TCB", "LST"],
                    ["SYD", "OOL"],
                    ["AXA", "OOL"],
                    ["AUA", "INN"],
                    ["OOL", "ANU"],
                    ["DRW", "SYD"],
                    ["SYD", "TCB"],
                    ["MHH", "ADL"],
                    ["JFK", "VIE"],
                    ["BNE", "ANU"],
                    ["LST", "CBR"],
                    ["VIE", "PER"],
                    ["ANU", "SYD"],
                    ["CBR", "CNS"],
                    ["DRW", "EZE"],
                    ["OOL", "MHH"],
                    ["VIE", "SYD"],
                    ["INN", "CBR"],
                    ["EZE", "MEL"],
                    ["DRW", "HBA"],
                    ["EZE", "INN"],
                    ["JFK", "TIA"],
                    ["SYD", "OOL"],
                    ["TIA", "VIE"],
                    ["AXA", "TIA"],
                    ["BNE", "HBA"],
                    ["AUA", "MHH"],
                    ["MEL", "CNS"],
                    ["HBA", "VIE"],
                    ["EZE", "JFK"],
                    ["AXA", "OOL"],
                    ["CNS", "CBR"],
                    ["VIE", "AUA"],
                    ["OOL", "INN"],
                    ["DRW", "ADL"],
                    ["OOL", "INN"],
                    ["MEL", "OOL"],
                    ["ADL", "MEL"],
                    ["INN", "ADL"],
                    ["TCB", "BAK"],
                    ["HBA", "SYD"],
                    ["EZE", "ANU"],
                    ["PER", "AUA"],
                    ["BAK", "DRW"],
                    ["JFK", "BAK"],
                    ["PER", "BNE"],
                    ["BNE", "JFK"],
                    ["CNS", "BAK"],
                    ["SYD", "OOL"],
                    ["MHH", "AXA"],
                    ["TCB", "VIE"],
                    ["TCB", "AXA"],
                    ["DRW", "CNS"],
                    ["BAK", "AUA"],
                    ["JFK", "BAK"],
                    ["MHH", "ANU"],
                    ["AUA", "TIA"],
                    ["LST", "AUA"],
                    ["CBR", "BNE"],
                    ["MHH", "DRW"],
                    ["BNE", "BAK"],
                    ["TIA", "AXA"],
                    ["AXA", "VIE"],
                    ["VIE", "AXA"],
                    ["SYD", "EZE"],
                    ["VIE", "AUA"],
                    ["PER", "JFK"],
                    ["VIE", "CBR"],
                    ["HBA", "VIE"],
                    ["CNS", "JFK"],
                    ["TCB", "VIE"],
                    ["CBR", "HBA"],
                    ["TCB", "CBR"],
                    ["EZE", "OOL"],
                    ["INN", "TCB"],
                    ["CBR", "TCB"],
                    ["HBA", "ADL"],
                    ["LST", "AUA"],
                    ["OOL", "JFK"],
                    ["PER", "CNS"],
                    ["MEL", "AXA"],
                    ["AXA", "SYD"],
                    ["JFK", "BNE"],
                    ["SYD", "TIA"],
                    ["TIA", "BNE"],
                    ["BNE", "AXA"],
                    ["AUA", "JFK"],
                    ["TCB", "EZE"],
                    ["TCB", "PER"],
                    ["VIE", "BAK"],
                ],
            ),
            [
                "JFK",
                "AUA",
                "BNE",
                "ANU",
                "AXA",
                "ANU",
                "CNS",
                "AXA",
                "BNE",
                "AUA",
                "BNE",
                "AXA",
                "BNE",
                "BAK",
                "AUA",
                "EZE",
                "ADL",
                "AXA",
                "EZE",
                "ANU",
                "DRW",
                "ADL",
                "BAK",
                "CNS",
                "AXA",
                "EZE",
                "AXA",
                "HBA",
                "ADL",
                "INN",
                "ADL",
                "INN",
                "BAK",
                "DRW",
                "ADL",
                "LST",
                "AUA",
                "EZE",
                "CBR",
                "ANU",
                "JFK",
                "AXA",
                "JFK",
                "BAK",
                "DRW",
                "BNE",
                "DRW",
                "CNS",
                "BAK",
                "EZE",
                "DRW",
                "EZE",
                "INN",
                "CBR",
                "AUA",
                "EZE",
                "JFK",
                "BAK",
                "HBA",
                "AUA",
                "INN",
                "DRW",
                "HBA",
                "AXA",
                "MEL",
                "AUA",
                "JFK",
                "BNE",
                "EZE",
                "LST",
                "AUA",
                "JFK",
                "BNE",
                "HBA",
                "JFK",
                "CBR",
                "BNE",
                "HBA",
                "MEL",
                "AXA",
                "OOL",
                "ADL",
                "MEL",
                "CNS",
                "CBR",
                "CNS",
                "INN",
                "DRW",
                "LST",
                "CBR",
                "DRW",
                "OOL",
                "ADL",
                "OOL",
                "ANU",
                "LST",
                "INN",
                "DRW",
                "SYD",
                "BNE",
                "JFK",
                "CNS",
                "JFK",
                "HBA",
                "OOL",
                "AXA",
                "OOL",
                "BAK",
                "LST",
                "PER",
                "ADL",
                "PER",
                "AUA",
                "MHH",
                "ADL",
                "SYD",
                "BNE",
                "JFK",
                "MHH",
                "ANU",
                "PER",
                "BAK",
                "MEL",
                "INN",
                "JFK",
                "TCB",
                "ADL",
                "TCB",
                "AXA",
                "SYD",
                "CNS",
                "JFK",
                "TCB",
                "BAK",
                "MEL",
                "INN",
                "MEL",
                "OOL",
                "BNE",
                "JFK",
                "TCB",
                "BNE",
                "LST",
                "SYD",
                "CNS",
                "LST",
                "SYD",
                "EZE",
                "MEL",
                "PER",
                "BNE",
                "MEL",
                "PER",
                "CBR",
                "HBA",
                "SYD",
                "EZE",
                "MHH",
                "AUA",
                "OOL",
                "EZE",
                "OOL",
                "HBA",
                "SYD",
                "INN",
                "MHH",
                "AXA",
                "TIA",
                "ADL",
                "TCB",
                "BNE",
                "OOL",
                "INN",
                "PER",
                "CNS",
                "MEL",
                "TCB",
                "CBR",
                "MEL",
                "TIA",
                "AUA",
                "PER",
                "CNS",
                "MHH",
                "AXA",
                "TIA",
                "AXA",
                "VIE",
                "ANU",
                "SYD",
                "JFK",
                "TIA",
                "BNE",
                "SYD",
                "MHH",
                "DRW",
                "SYD",
                "OOL",
                "INN",
                "TCB",
                "EZE",
                "PER",
                "EZE",
                "SYD",
                "OOL",
                "INN",
                "VIE",
                "ANU",
                "TCB",
                "LST",
                "VIE",
                "AUA",
                "TIA",
                "BNE",
                "TCB",
                "MHH",
                "HBA",
                "TCB",
                "PER",
                "JFK",
                "VIE",
                "AUA",
                "VIE",
                "AXA",
                "VIE",
                "BAK",
                "PER",
                "OOL",
                "MHH",
                "SYD",
                "OOL",
                "VIE",
                "BAK",
                "SYD",
                "PER",
                "SYD",
                "TCB",
                "PER",
                "SYD",
                "TCB",
                "TIA",
                "CBR",
                "TCB",
                "VIE",
                "BAK",
                "VIE",
                "CBR",
                "VIE",
                "CNS",
                "VIE",
                "HBA",
                "VIE",
                "MEL",
                "TIA",
                "HBA",
                "VIE",
                "MHH",
                "VIE",
                "PER",
                "TIA",
                "TCB",
                "VIE",
                "PER",
                "TIA",
                "VIE",
                "TCB",
                "VIE",
                "SYD",
                "TIA",
                "OOL",
                "JFK",
            ],
            # 8
        ),
    ],
)
def test(inp, expected, request):
    test_id = request.node.callspec.id

    file_ = pathlib.Path(__file__)
    path = file_.parent / (file_.stem + f"-test-{test_id}.txt")
    with path.open("w") as f:
        assert main(**inp, f=f) == expected


if __name__ == "__main__":
    main(
        tickets=[
            ["HBA", "MEL"],
            ["ASD", "CNS"],
            ["AXA", "SYD"],
            ["BIM", "TIA"],
            ["AUA", "TCB"],
            ["TBI", "BZE"],
            ["PER", "CBR"],
            ["CNS", "TCB"],
            ["ADL", "ASD"],
            ["ELH", "BAK"],
            ["HBA", "OOL"],
            ["CBR", "ADL"],
            ["CNS", "AUA"],
            ["ADL", "TBI"],
            ["MEL", "TBI"],
            ["ELH", "BAK"],
            ["TIA", "BNE"],
            ["ANU", "VIE"],
            ["TCB", "BAK"],
            ["TCB", "ADL"],
            ["VIE", "TCB"],
            ["BAK", "VIE"],
            ["ASD", "PER"],
            ["INN", "HBA"],
            ["TCB", "LST"],
            ["CNS", "DRW"],
            ["DRW", "AXA"],
            ["ANU", "CNS"],
            ["SYD", "BNE"],
            ["ADL", "SYD"],
            ["MEL", "SYD"],
            ["MHH", "TIA"],
            ["TIA", "ADL"],
            ["DRW", "TCB"],
            ["ADL", "EZE"],
            ["INN", "MHH"],
            ["BIM", "TIA"],
            ["HBA", "AXA"],
            ["INN", "CNS"],
            ["INN", "TBI"],
            ["TCB", "AXA"],
            ["EZE", "ADL"],
            ["DRW", "HBA"],
            ["DRW", "EZE"],
            ["TIA", "OOL"],
            ["OOL", "BAK"],
            ["VIE", "BAK"],
            ["HBA", "SYD"],
            ["ADL", "CBR"],
            ["SYD", "BIM"],
            ["AXA", "DRW"],
            ["AXA", "MHH"],
            ["SYD", "TCB"],
            ["TIA", "CNS"],
            ["MEL", "BIM"],
            ["TCB", "TIA"],
            ["JFK", "INN"],
            ["CNS", "ADL"],
            ["BNE", "SYD"],
            ["DRW", "SYD"],
            ["AXA", "ASD"],
            ["TBI", "BAK"],
            ["BIM", "MEL"],
            ["PER", "ASD"],
            ["BAK", "DRW"],
            ["BNE", "DRW"],
            ["ASD", "TIA"],
            ["ADL", "EZE"],
            ["PER", "TCB"],
            ["DRW", "OOL"],
            ["SYD", "ADL"],
            ["EZE", "CNS"],
            ["ASD", "CBR"],
            ["ADL", "VIE"],
            ["TBI", "DRW"],
            ["CBR", "OOL"],
            ["ASD", "TCB"],
            ["JFK", "MEL"],
            ["BAK", "JFK"],
            ["SYD", "PER"],
            ["ASD", "MHH"],
            ["TCB", "ELH"],
            ["BAK", "ELH"],
            ["ELH", "OOL"],
            ["CBR", "BAK"],
            ["ELH", "ANU"],
            ["PER", "AXA"],
            ["VIE", "ANU"],
            ["MEL", "HBA"],
            ["TIA", "SYD"],
            ["SYD", "CBR"],
            ["SYD", "JFK"],
            ["BNE", "TIA"],
            ["MEL", "DRW"],
            ["SYD", "MEL"],
            ["TIA", "BNE"],
            ["TBI", "CNS"],
            ["SYD", "HBA"],
            ["LST", "OOL"],
            ["ANU", "MEL"],
            ["JFK", "ASD"],
            ["VIE", "TBI"],
            ["CBR", "CNS"],
            ["LST", "BNE"],
            ["ASD", "HBA"],
            ["ANU", "INN"],
            ["PER", "TCB"],
            ["MEL", "BAK"],
            ["TIA", "MHH"],
            ["BAK", "ELH"],
            ["TBI", "EZE"],
            ["ADL", "AXA"],
            ["AXA", "CNS"],
            ["BNE", "PER"],
            ["ADL", "MEL"],
            ["ADL", "EZE"],
            ["ASD", "JFK"],
            ["MEL", "ELH"],
            ["TIA", "TBI"],
            ["TCB", "ASD"],
            ["JFK", "BNE"],
            ["ADL", "CNS"],
            ["MEL", "HBA"],
            ["TIA", "BIM"],
            ["MEL", "AXA"],
            ["ELH", "HBA"],
            ["OOL", "HBA"],
            ["CBR", "MHH"],
            ["LST", "SYD"],
            ["HBA", "ADL"],
            ["CBR", "JFK"],
            ["ELH", "LST"],
            ["BIM", "TCB"],
            ["SYD", "HBA"],
            ["CBR", "VIE"],
            ["MEL", "TCB"],
            ["HBA", "ANU"],
            ["VIE", "ELH"],
            ["HBA", "INN"],
            ["CNS", "LST"],
            ["OOL", "DRW"],
            ["LST", "PER"],
            ["SYD", "AXA"],
            ["AXA", "VIE"],
            ["ANU", "DRW"],
            ["ELH", "TIA"],
            ["BAK", "ASD"],
            ["HBA", "OOL"],
            ["ADL", "BIM"],
            ["EZE", "MEL"],
            ["CBR", "MEL"],
            ["DRW", "ASD"],
            ["TCB", "DRW"],
            ["ELH", "MHH"],
            ["EZE", "JFK"],
            ["ASD", "CBR"],
            ["AXA", "INN"],
            ["CNS", "TIA"],
            ["TBI", "AUA"],
            ["MHH", "LST"],
            ["INN", "BIM"],
            ["ADL", "EZE"],
            ["PER", "ADL"],
            ["PER", "ADL"],
            ["AXA", "TCB"],
            ["HBA", "ELH"],
            ["ADL", "DRW"],
            ["BAK", "LST"],
            ["CNS", "INN"],
            ["BIM", "VIE"],
            ["TCB", "TBI"],
            ["EZE", "ADL"],
            ["CBR", "INN"],
            ["SYD", "TCB"],
            ["ADL", "ASD"],
            ["BAK", "ASD"],
            ["ASD", "VIE"],
            ["MHH", "CBR"],
            ["DRW", "HBA"],
            ["MEL", "TIA"],
            ["PER", "TIA"],
            ["BIM", "TCB"],
            ["TIA", "ADL"],
            ["TBI", "BIM"],
            ["VIE", "OOL"],
            ["JFK", "PER"],
            ["TBI", "TCB"],
            ["HBA", "ANU"],
            ["TCB", "MEL"],
            ["TIA", "VIE"],
            ["CNS", "BAK"],
            ["VIE", "ASD"],
            ["ELH", "SYD"],
            ["MHH", "ELH"],
            ["HBA", "ADL"],
            ["LST", "CNS"],
            ["INN", "ELH"],
            ["EZE", "HBA"],
            ["MEL", "INN"],
            ["VIE", "INN"],
            ["ADL", "CBR"],
            ["ADL", "JFK"],
            ["OOL", "TCB"],
            ["HBA", "ADL"],
            ["CBR", "EZE"],
            ["BNE", "SYD"],
            ["ELH", "DRW"],
            ["OOL", "LST"],
            ["DRW", "ASD"],
            ["BNE", "ADL"],
            ["TCB", "PER"],
            ["OOL", "VIE"],
            ["AUA", "HBA"],
            ["HBA", "TIA"],
            ["TBI", "AUA"],
            ["EZE", "SYD"],
            ["AXA", "PER"],
            ["OOL", "MHH"],
            ["CBR", "ELH"],
            ["TCB", "VIE"],
            ["MHH", "ELH"],
            ["TBI", "HBA"],
            ["HBA", "AXA"],
            ["ASD", "MEL"],
            ["TIA", "ANU"],
            ["VIE", "ADL"],
            ["AXA", "TBI"],
            ["EZE", "ANU"],
            ["CBR", "BNE"],
            ["BNE", "TIA"],
            ["OOL", "VIE"],
            ["AXA", "PER"],
            ["DRW", "ADL"],
            ["JFK", "TIA"],
            ["TIA", "CNS"],
            ["INN", "MEL"],
            ["BAK", "HBA"],
            ["BIM", "HBA"],
            ["VIE", "SYD"],
            ["OOL", "TIA"],
            ["VIE", "DRW"],
            ["CNS", "TBI"],
            ["AUA", "LST"],
            ["TCB", "BIM"],
            ["BIM", "TBI"],
            ["TIA", "JFK"],
            ["VIE", "CBR"],
            ["HBA", "AXA"],
            ["HBA", "BAK"],
            ["JFK", "DRW"],
            ["INN", "CNS"],
            ["ANU", "VIE"],
            ["EZE", "HBA"],
            ["INN", "BNE"],
            ["ADL", "MEL"],
            ["PER", "ANU"],
            ["TCB", "TBI"],
            ["MEL", "CBR"],
            ["DRW", "AXA"],
            ["CBR", "OOL"],
            ["BAK", "TIA"],
            ["SYD", "PER"],
            ["LST", "ADL"],
            ["CNS", "INN"],
            ["ANU", "CBR"],
            ["MHH", "EZE"],
            ["DRW", "MEL"],
            ["CNS", "ELH"],
            ["TCB", "EZE"],
            ["DRW", "SYD"],
            ["ADL", "DRW"],
            ["ANU", "OOL"],
            ["ELH", "CBR"],
            ["TIA", "CBR"],
            ["VIE", "ADL"],
            ["DRW", "AXA"],
            ["TCB", "ADL"],
            ["CNS", "VIE"],
            ["MHH", "ANU"],
            ["JFK", "TCB"],
            ["LST", "CBR"],
            ["OOL", "BIM"],
        ],
    )
