"""
https://leetcode.com/problems/reconstruct-itinerary/description/?envType=problem-list-v2&envId=graph
"""

import collections
import copy

import pytest


class Solution:
    @staticmethod
    def _get_possible_dst(src, left_tickets, itinerary_for_debug):
        def reachable(c, updated_left_tickets):
            for destinations in updated_left_tickets.values():
                if c in destinations:
                    return True
            return False

        candidates = left_tickets[src]
        final_candidates = []
        for candidate in candidates:
            # if itinerary_for_debug == ["JFK", "SFO", "JFK", "ATL"] and candidate == "AAA":
            #     debug = True  # debug case inp2 (starting from 0)
            updated_left_tickets = copy.deepcopy(left_tickets)
            updated_left_tickets[src].remove(candidate)
            if not updated_left_tickets[src]:
                updated_left_tickets.pop(src)

            # check that any left candidate is reachable
            other_candidates = [c for c in candidates if c != candidate]

            for another_candidate in other_candidates:
                left_tickets_except_another = copy.deepcopy(updated_left_tickets)
                left_tickets_except_another[src].remove(another_candidate)
                if not left_tickets_except_another[src]:
                    left_tickets_except_another.pop(src)

                # we want every another is reachable from the rest part of this graph (with src - another_candidate edge cutted)
                another_is_reachable_not_from_src = reachable(another_candidate, left_tickets_except_another)
                if another_is_reachable_not_from_src:
                    continue

                # but it's not always possible. another way is to get back to src at least and go to another from src.
                # so now but branch another->src (if exists) and check src is still reachable from our cutted graph left
                left_tickets_except_src_from_another = copy.deepcopy(updated_left_tickets)
                if src in left_tickets_except_src_from_another.get(another_candidate, []):
                    left_tickets_except_src_from_another[another_candidate].remove(src)
                    if not left_tickets_except_src_from_another[another_candidate]:
                        left_tickets_except_src_from_another.pop(another_candidate)
                if reachable(src, left_tickets_except_src_from_another):
                    continue
                else:
                    break
            else:
                final_candidates.append(candidate)

        # now we need to sort them to first pick those who have more destinations from it, then alphabetically
        # # # TODO its a good idea - result if faster but not its not alphabetically best :(
        # sorted_candidates = sorted(final_candidates, key=lambda c: (-len(left_tickets.get(c, [])), c))
        # return sorted_candidates
        return final_candidates

    def findItinerary(self, tickets: list[list[str]], f=None) -> list[str]:
        if f:
            # debug mode
            import time

            s = time.time()
        _adj_list: collections.defaultdict[str, list[str]] = collections.defaultdict(list)
        for u, v in tickets:
            _adj_list[u].append(v)
        adj_list: dict[str, list[str]] = {u: sorted(v) for u, v in _adj_list.items()}

        # TODO for inp4 it's no more true! now check it breaks smth...
        # # check if only 1 ticket between any 2 cities exists
        # for u, vs in adj_list.items():
        #     if len(set(vs)) != len(vs):
        #         raise ValueError(f"many tickets from {u} detected: {[x for x in vs]}")

        start = "JFK"

        start_itinerary = [start]
        probe = 0

        def dfs(src, left_tickets, itinerary, level):
            if not left_tickets:
                return itinerary

            if not left_tickets.get(src):
                return None

            if left_tickets[src]:
                possible_dst = list(self._get_possible_dst(src, left_tickets, itinerary))

                for dst in possible_dst:
                    updated_left_tickets = copy.deepcopy(left_tickets)
                    updated_left_tickets[src].remove(dst)
                    if not updated_left_tickets[src]:
                        updated_left_tickets.pop(src)

                    if f:
                        print(f"{time.time() - s} seconds. considering {dst} from {itinerary}...", file=f)
                    new_itinerary = dfs(dst, updated_left_tickets, itinerary + [dst], level + 1)
                    if new_itinerary is not None:
                        # if f: print(f"{time.time() - s} seconds. good: considered {dst} from {itinerary}...", file=f)
                        return new_itinerary
                    # else:
                    # if f: print(f"{time.time() - s} seconds. bad : considered {dst} from {itinerary}...", file=f)

            nonlocal probe
            if f:
                print(
                    f"{time.time() - s} seconds. {probe=}. lvl={level}. "
                    f"left={sum([len(v) for v in left_tickets.values()])}: {left_tickets} for\n"
                    f"{itinerary} len of {len(itinerary)}",
                    file=f,
                )
            probe += 1
            return None

        final_itinerary = dfs(start, adj_list, start_itinerary, level=0)
        if f:
            print(f"{time.time() - s} seconds. {probe=}. success:\n{final_itinerary}", file=f)
        return final_itinerary


def main(tickets: list[list[str]], f=None) -> list[str]:
    return Solution().findItinerary(tickets, f)


@pytest.mark.parametrize(
    "inp,expected",
    [
        pytest.param(
            dict(tickets=[["MUC", "LHR"], ["JFK", "MUC"], ["SFO", "SJC"], ["LHR", "SFO"]]),
            ["JFK", "MUC", "LHR", "SFO", "SJC"],
        ),
        pytest.param(
            dict(tickets=[["JFK", "SFO"], ["JFK", "ATL"], ["SFO", "ATL"], ["ATL", "JFK"], ["ATL", "SFO"]]),
            ["JFK", "ATL", "JFK", "SFO", "ATL", "SFO"],
        ),
        pytest.param(
            dict(
                tickets=[
                    ["JFK", "SFO"],
                    ["JFK", "ATL"],
                    ["SFO", "JFK"],
                    ["ATL", "AAA"],
                    ["AAA", "ATL"],
                    ["ATL", "BBB"],
                    ["BBB", "ATL"],
                    ["ATL", "CCC"],
                    ["CCC", "ATL"],
                    ["ATL", "DDD"],
                    ["DDD", "ATL"],
                    ["ATL", "EEE"],
                    ["EEE", "ATL"],
                    ["ATL", "FFF"],
                    ["FFF", "ATL"],
                    ["ATL", "GGG"],
                    ["GGG", "ATL"],
                    ["ATL", "HHH"],
                    ["HHH", "ATL"],
                    ["ATL", "III"],
                    ["III", "ATL"],
                    ["ATL", "JJJ"],
                    ["JJJ", "ATL"],
                    ["ATL", "KKK"],
                    ["KKK", "ATL"],
                    ["ATL", "LLL"],
                    ["LLL", "ATL"],
                    ["ATL", "MMM"],
                    ["MMM", "ATL"],
                    ["ATL", "NNN"],
                    ["NNN", "ATL"],
                ],
            ),
            [
                "JFK",
                "SFO",
                "JFK",
                "ATL",
                "AAA",
                "ATL",
                "BBB",
                "ATL",
                "CCC",
                "ATL",
                "DDD",
                "ATL",
                "EEE",
                "ATL",
                "FFF",
                "ATL",
                "GGG",
                "ATL",
                "HHH",
                "ATL",
                "III",
                "ATL",
                "JJJ",
                "ATL",
                "KKK",
                "ATL",
                "LLL",
                "ATL",
                "MMM",
                "ATL",
                "NNN",
                "ATL",
            ],
        ),
        pytest.param(
            dict(tickets=[["JFK", "KUL"], ["JFK", "NRT"], ["NRT", "JFK"]]),
            ["JFK", "NRT", "JFK", "KUL"],
        ),
        pytest.param(
            dict(
                tickets=[
                    ["EZE", "AXA"],
                    ["TIA", "ANU"],
                    ["ANU", "JFK"],
                    ["JFK", "ANU"],
                    ["ANU", "EZE"],
                    ["TIA", "ANU"],
                    ["AXA", "TIA"],
                    ["TIA", "JFK"],
                    ["ANU", "TIA"],
                    ["JFK", "TIA"],
                ],
            ),
            ["JFK", "ANU", "EZE", "AXA", "TIA", "ANU", "JFK", "TIA", "ANU", "TIA", "JFK"],
        ),
        pytest.param(
            dict(
                tickets=[
                    ["AUA", "EZE"],
                    ["JFK", "AUA"],
                    ["EZE", "ANU"],
                    ["AXA", "JFK"],
                    ["AUA", "JFK"],
                    ["ADL", "TIA"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["AUA", "AXA"],
                    ["AXA", "TIA"],
                    ["EZE", "AXA"],
                    ["AXA", "AUA"],
                    ["ANU", "JFK"],
                    ["ADL", "EZE"],
                    ["ADL", "ANU"],
                    ["EZE", "ADL"],
                    ["AXA", "AUA"],
                    ["JFK", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["AXA", "JFK"],
                    ["ADL", "EZE"],
                    ["AUA", "EZE"],
                    ["AUA", "JFK"],
                    ["AUA", "JFK"],
                    ["JFK", "AXA"],
                    ["TIA", "AXA"],
                    ["JFK", "ADL"],
                    ["ADL", "AXA"],
                    ["AXA", "AUA"],
                    ["AUA", "AXA"],
                    ["JFK", "AXA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["JFK", "AXA"],
                    ["EZE", "AXA"],
                    ["AXA", "EZE"],
                    ["JFK", "ADL"],
                    ["EZE", "AXA"],
                    ["ANU", "AXA"],
                    ["AXA", "JFK"],
                    ["JFK", "AUA"],
                    ["AXA", "EZE"],
                    ["ADL", "AXA"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["AXA", "AUA"],
                    ["ADL", "ANU"],
                    ["ANU", "AUA"],
                    ["ADL", "ANU"],
                    ["JFK", "ADL"],
                    ["TIA", "AUA"],
                    ["EZE", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "ADL"],
                    ["JFK", "ANU"],
                    ["ADL", "ANU"],
                    ["TIA", "AUA"],
                    ["ADL", "ANU"],
                    ["AUA", "EZE"],
                    ["JFK", "ANU"],
                    ["AUA", "ANU"],
                    ["ADL", "AUA"],
                    ["JFK", "ADL"],
                    ["TIA", "JFK"],
                    ["AXA", "ANU"],
                    ["AXA", "ANU"],
                    ["JFK", "AXA"],
                    ["AXA", "JFK"],
                    ["ANU", "AXA"],
                    ["ADL", "EZE"],
                    ["JFK", "ANU"],
                    ["JFK", "AUA"],
                    ["AXA", "ANU"],
                    ["JFK", "TIA"],
                    ["ANU", "AXA"],
                    ["JFK", "AUA"],
                    ["AXA", "AUA"],
                    ["ADL", "EZE"],
                    ["ADL", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "AUA"],
                    ["AUA", "ADL"],
                    ["JFK", "ADL"],
                    ["EZE", "TIA"],
                    ["TIA", "AXA"],
                    ["AUA", "ADL"],
                    ["JFK", "AUA"],
                    ["JFK", "AUA"],
                    ["AUA", "ANU"],
                    ["JFK", "ADL"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "ADL"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["EZE", "ANU"],
                    ["AUA", "ANU"],
                    ["JFK", "EZE"],
                    ["EZE", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["TIA", "JFK"],
                    ["ANU", "AXA"],
                    ["TIA", "ANU"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["AXA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "ANU"],
                    ["EZE", "AXA"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AUA", "ADL"],
                    ["AUA", "ADL"],
                    ["TIA", "JFK"],
                    ["JFK", "AUA"],
                    ["ADL", "AUA"],
                    ["AXA", "TIA"],
                    ["AXA", "TIA"],
                    ["AXA", "ANU"],
                    ["AUA", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AUA"],
                    ["ANU", "TIA"],
                    ["AUA", "AXA"],
                    ["ANU", "TIA"],
                    ["AXA", "AUA"],
                    ["EZE", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "EZE"],
                    ["AXA", "JFK"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["AUA", "AXA"],
                    ["JFK", "TIA"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["ANU", "AXA"],
                    ["EZE", "ADL"],
                    ["ADL", "ANU"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "HBA"],
                    ["JFK", "AUA"],
                    ["TIA", "AUA"],
                    ["TIA", "ADL"],
                    ["AXA", "ADL"],
                    ["EZE", "AUA"],
                    ["EZE", "JFK"],
                    ["ANU", "TIA"],
                    ["ANU", "JFK"],
                    ["EZE", "AUA"],
                    ["EZE", "AUA"],
                    ["ADL", "JFK"],
                    ["ADL", "AUA"],
                    ["ADL", "AXA"],
                    ["AXA", "JFK"],
                    ["AXA", "AUA"],
                    ["ANU", "AUA"],
                    ["ANU", "JFK"],
                    ["TIA", "EZE"],
                    ["ANU", "AUA"],
                    ["ADL", "JFK"],
                    ["JFK", "ANU"],
                    ["ADL", "JFK"],
                    ["ANU", "AUA"],
                    ["JFK", "ADL"],
                    ["AXA", "ANU"],
                    ["AXA", "JFK"],
                    ["JFK", "ADL"],
                    ["EZE", "JFK"],
                    ["TIA", "AUA"],
                    ["ANU", "ADL"],
                    ["AUA", "AXA"],
                    ["ADL", "AXA"],
                    ["AUA", "JFK"],
                    ["ADL", "AXA"],
                    ["EZE", "ANU"],
                    ["TIA", "EZE"],
                    ["EZE", "JFK"],
                    ["ADL", "EZE"],
                    ["ANU", "JFK"],
                    ["AUA", "JFK"],
                    ["ANU", "JFK"],
                    ["EZE", "ADL"],
                    ["AUA", "ADL"],
                    ["EZE", "ANU"],
                    ["AXA", "EZE"],
                    ["AXA", "ADL"],
                    ["JFK", "TIA"],
                    ["AUA", "ADL"],
                    ["EZE", "TIA"],
                    ["AXA", "EZE"],
                    ["EZE", "AUA"],
                    ["JFK", "TIA"],
                    ["AUA", "AXA"],
                    ["TIA", "ANU"],
                    ["AXA", "JFK"],
                    ["TIA", "EZE"],
                    ["EZE", "ANU"],
                    ["ANU", "EZE"],
                    ["JFK", "TIA"],
                    ["JFK", "EZE"],
                    ["TIA", "AXA"],
                    ["ANU", "EZE"],
                    ["AUA", "TIA"],
                    ["AXA", "EZE"],
                    ["ANU", "AUA"],
                    ["AUA", "EZE"],
                    ["AUA", "EZE"],
                    ["ADL", "ANU"],
                    ["AUA", "AXA"],
                    ["AXA", "ADL"],
                    ["JFK", "EZE"],
                ],
            ),
            [
                "JFK",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "ANU",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ADL",
                "AUA",
                "ANU",
                "AUA",
                "ANU",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ADL",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "ANU",
                "AXA",
                "AUA",
                "ANU",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "AUA",
                "AXA",
                "EZE",
                "ADL",
                "AXA",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ADL",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "ANU",
                "JFK",
                "ADL",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "AXA",
                "EZE",
                "AUA",
                "EZE",
                "AUA",
                "EZE",
                "AXA",
                "EZE",
                "AXA",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ADL",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "JFK",
                "ANU",
                "TIA",
                "ADL",
                "TIA",
                "ANU",
                "TIA",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "ANU",
                "TIA",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "EZE",
                "AXA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AUA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "AXA",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "EZE",
                "JFK",
                "TIA",
                "AUA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "AXA",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "JFK",
                "TIA",
                "EZE",
                "TIA",
                "EZE",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "JFK",
                "TIA",
                "AUA",
                "HBA",
            ],
        ),
    ],
)
def test(inp, expected, request):
    test_id = request.node.callspec.id
    import pathlib

    file_ = pathlib.Path(__file__)
    path = file_.parent / (file_.stem + f"-test-{test_id}.txt")
    with path.open("w") as f:
        assert main(**inp, f=f) == expected


if __name__ == "__main__":
    main(
        tickets=[
            ["AUA", "EZE"],
            ["JFK", "AUA"],
            ["EZE", "ANU"],
            ["AXA", "JFK"],
            ["AUA", "JFK"],
            ["ADL", "TIA"],
            ["AUA", "AXA"],
            ["ADL", "AUA"],
            ["AUA", "AXA"],
            ["AXA", "TIA"],
            ["EZE", "AXA"],
            ["AXA", "AUA"],
            ["ANU", "JFK"],
            ["ADL", "EZE"],
            ["ADL", "ANU"],
            ["EZE", "ADL"],
            ["AXA", "AUA"],
            ["JFK", "EZE"],
            ["AUA", "JFK"],
            ["AUA", "JFK"],
            ["AXA", "JFK"],
            ["ADL", "EZE"],
            ["AUA", "EZE"],
            ["AUA", "JFK"],
            ["AUA", "JFK"],
            ["JFK", "AXA"],
            ["TIA", "AXA"],
            ["JFK", "ADL"],
            ["ADL", "AXA"],
            ["AXA", "AUA"],
            ["AUA", "AXA"],
            ["JFK", "AXA"],
            ["TIA", "JFK"],
            ["ANU", "AXA"],
            ["JFK", "AXA"],
            ["EZE", "AXA"],
            ["AXA", "EZE"],
            ["JFK", "ADL"],
            ["EZE", "AXA"],
            ["ANU", "AXA"],
            ["AXA", "JFK"],
            ["JFK", "AUA"],
            ["AXA", "EZE"],
            ["ADL", "AXA"],
            ["AUA", "ADL"],
            ["AUA", "ADL"],
            ["AXA", "AUA"],
            ["ADL", "ANU"],
            ["ANU", "AUA"],
            ["ADL", "ANU"],
            ["JFK", "ADL"],
            ["TIA", "AUA"],
            ["EZE", "AXA"],
            ["ANU", "TIA"],
            ["AXA", "ADL"],
            ["JFK", "ANU"],
            ["ADL", "ANU"],
            ["TIA", "AUA"],
            ["ADL", "ANU"],
            ["AUA", "EZE"],
            ["JFK", "ANU"],
            ["AUA", "ANU"],
            ["ADL", "AUA"],
            ["JFK", "ADL"],
            ["TIA", "JFK"],
            ["AXA", "ANU"],
            ["AXA", "ANU"],
            ["JFK", "AXA"],
            ["AXA", "JFK"],
            ["ANU", "AXA"],
            ["ADL", "EZE"],
            ["JFK", "ANU"],
            ["JFK", "AUA"],
            ["AXA", "ANU"],
            ["JFK", "TIA"],
            ["ANU", "AXA"],
            ["JFK", "AUA"],
            ["AXA", "AUA"],
            ["ADL", "EZE"],
            ["ADL", "AXA"],
            ["JFK", "TIA"],
            ["EZE", "AUA"],
            ["AUA", "ADL"],
            ["JFK", "ADL"],
            ["EZE", "TIA"],
            ["TIA", "AXA"],
            ["AUA", "ADL"],
            ["JFK", "AUA"],
            ["JFK", "AUA"],
            ["AUA", "ANU"],
            ["JFK", "ADL"],
            ["AXA", "AUA"],
            ["EZE", "JFK"],
            ["ANU", "ADL"],
            ["ADL", "EZE"],
            ["ANU", "JFK"],
            ["EZE", "ANU"],
            ["AUA", "ANU"],
            ["JFK", "EZE"],
            ["EZE", "JFK"],
            ["AXA", "AUA"],
            ["ANU", "AUA"],
            ["TIA", "JFK"],
            ["ANU", "AXA"],
            ["TIA", "ANU"],
            ["AUA", "ADL"],
            ["ANU", "AXA"],
            ["AXA", "ADL"],
            ["AUA", "AXA"],
            ["ADL", "ANU"],
            ["EZE", "AXA"],
            ["EZE", "ANU"],
            ["AXA", "EZE"],
            ["AUA", "ADL"],
            ["AUA", "ADL"],
            ["TIA", "JFK"],
            ["JFK", "AUA"],
            ["ADL", "AUA"],
            ["AXA", "TIA"],
            ["AXA", "TIA"],
            ["AXA", "ANU"],
            ["AUA", "ADL"],
            ["AUA", "AXA"],
            ["ADL", "AUA"],
            ["ANU", "TIA"],
            ["AUA", "AXA"],
            ["ANU", "TIA"],
            ["AXA", "AUA"],
            ["EZE", "JFK"],
            ["ADL", "AUA"],
            ["ADL", "EZE"],
            ["AXA", "JFK"],
            ["JFK", "TIA"],
            ["AUA", "AXA"],
            ["AUA", "AXA"],
            ["JFK", "TIA"],
            ["EZE", "ADL"],
            ["AUA", "ADL"],
            ["ANU", "AXA"],
            ["EZE", "ADL"],
            ["ADL", "ANU"],
            ["TIA", "EZE"],
            ["ANU", "AUA"],
            ["AUA", "HBA"],
            ["JFK", "AUA"],
            ["TIA", "AUA"],
            ["TIA", "ADL"],
            ["AXA", "ADL"],
            ["EZE", "AUA"],
            ["EZE", "JFK"],
            ["ANU", "TIA"],
            ["ANU", "JFK"],
            ["EZE", "AUA"],
            ["EZE", "AUA"],
            ["ADL", "JFK"],
            ["ADL", "AUA"],
            ["ADL", "AXA"],
            ["AXA", "JFK"],
            ["AXA", "AUA"],
            ["ANU", "AUA"],
            ["ANU", "JFK"],
            ["TIA", "EZE"],
            ["ANU", "AUA"],
            ["ADL", "JFK"],
            ["JFK", "ANU"],
            ["ADL", "JFK"],
            ["ANU", "AUA"],
            ["JFK", "ADL"],
            ["AXA", "ANU"],
            ["AXA", "JFK"],
            ["JFK", "ADL"],
            ["EZE", "JFK"],
            ["TIA", "AUA"],
            ["ANU", "ADL"],
            ["AUA", "AXA"],
            ["ADL", "AXA"],
            ["AUA", "JFK"],
            ["ADL", "AXA"],
            ["EZE", "ANU"],
            ["TIA", "EZE"],
            ["EZE", "JFK"],
            ["ADL", "EZE"],
            ["ANU", "JFK"],
            ["AUA", "JFK"],
            ["ANU", "JFK"],
            ["EZE", "ADL"],
            ["AUA", "ADL"],
            ["EZE", "ANU"],
            ["AXA", "EZE"],
            ["AXA", "ADL"],
            ["JFK", "TIA"],
            ["AUA", "ADL"],
            ["EZE", "TIA"],
            ["AXA", "EZE"],
            ["EZE", "AUA"],
            ["JFK", "TIA"],
            ["AUA", "AXA"],
            ["TIA", "ANU"],
            ["AXA", "JFK"],
            ["TIA", "EZE"],
            ["EZE", "ANU"],
            ["ANU", "EZE"],
            ["JFK", "TIA"],
            ["JFK", "EZE"],
            ["TIA", "AXA"],
            ["ANU", "EZE"],
            ["AUA", "TIA"],
            ["AXA", "EZE"],
            ["ANU", "AUA"],
            ["AUA", "EZE"],
            ["AUA", "EZE"],
            ["ADL", "ANU"],
            ["AUA", "AXA"],
            ["AXA", "ADL"],
            ["JFK", "EZE"],
        ],
    )
